let
    Source = SharePoint.Files("https://bcgov.sharepoint.com/sites/AF-SICI", [ApiVersion = 15]),
    #"Trade_Import_Commodity_Classification csv_https://bcgov sharepoint com/sites/AF-SICI/Raw Data/" = Source{[Name="Trade_Import_Commodity_Classification.csv",#"Folder Path"="https://bcgov.sharepoint.com/sites/AF-SICI/Raw Data/"]}[Content],
    #"Imported CSV" = Csv.Document(#"Trade_Import_Commodity_Classification csv_https://bcgov sharepoint com/sites/AF-SICI/Raw Data/",[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Sector", type text}, {"Sub-Sector", type text}, {"Commodity Group", type text}, {"Commodity_Detail", type text}, {"HS10", type text}, {"HS10_code", type text}, {"NAICS6", type text}, {"NAICS6_Code", type text}, {"NAICS5_Code", type text}, {"NAICS4_Code", type text}, {"NAICS3_Code", type text}}),
    #"Inserted First Characters" = Table.AddColumn(#"Changed Type", "HS8", each Text.Start([HS10_code], 8), type text),
    #"Inserted First Characters1" = Table.AddColumn(#"Inserted First Characters", "HS6", each Text.Start([HS8], 6), type text),
    #"Inserted First Characters2" = Table.AddColumn(#"Inserted First Characters1", "HS4", each Text.Start([HS6], 4), type text),
    #"Inserted First Characters3" = Table.AddColumn(#"Inserted First Characters2", "HS2", each Text.Start([HS4], 2), type text)
in
    #"Inserted First Characters3"
